### ISSUE TITLE
Make `DebugWarnIfCostIncreases` not call objective when possible

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#171]
Since objective is usually calculated in `perform_step!`, it should be possible to reuse the computed value for `DebugWarnIfCostIncreases` instead of recomputing it.

**Comment by kellertuer** [comment]
Yes that sounds reasonable, though (if I remember the warning correctly) the default is, that it is only warning once, but sure if it always runs and never issues a warning, that is a few cost evaluations.
I was – until now – not so careful about the number of cost evals.

We also thought about using another step size as default, but the Armco stepwise is both a little costly itself and might not work on all manifolds , that is why we switched to the constant one, which does not guarantee descent.


I am also not sure where to store the cost, but that could be done in the common `storage` struct, the debug informations usually share.

**Comment by kellertuer** [comment]
One thing that we could do is – to make `get_cost` (and `get_gradient`and all other access-functions) into functions that also can have a storage.

For that I would like to build two layers I think

1. how the value / data is actually computed (that is the current get_cost`)
2. a function that encapsulates that, is a functor itself, so has the same idea of a `storage` as the debugs, and if a certain field is present, the cost is stored.

The second could even behave different for different fields being present, i.e. just one evaluation as cache or all; just in case someone comes along and asks for some old cost/grad.

This would be quite some work, probably breaking, since I think the function in 2) should then be called `get_cost` and the first one maybe `compute_cost` or `evaluate_cost`. Also, I would like to maybe check whether the design of the storage is efficient and change that?

But overall sounds like a neat project / improvement.

**Comment by mateuszbaran** [comment]
> We also thought about using another step size as default, but the Armco stepwise is both a little costly itself and might not work on all manifolds , that is why we switched to the constant one, which does not guarantee descent.

Yes, but that's a separate issue.

> I am also not sure where to store the cost, but that could be done in the common `storage` struct, the debug informations usually share.

Maybe solver options should just cache the cost? That's what I actually had in mind when opening this issue. For example `LevenbergMarquardtOptions` currently computes cost for the new candidate point so if it's accepted we could store it for the next step. That would mean this stored value could have double use.

**Comment by kellertuer** [comment]
Sure that is a different issue – currently it is what it is.

For storing it in the options, I have three points

1. The gradient descent for example does not store its old iterate or gradient (just the stopping criteria do) because they never need it actively (the stopping criteria do)
2. If your algorithm needs that value sure you can store it
3. combining both: I would like to avoid storing it there in general, that is why I wrote about storing it in the `storage`.

So if it has use for you sure store it. For the general case (i.e. using it within any debug/record/stop) I would prefer a storage – I would like to avoid changing all options as well.

**Comment by mateuszbaran** [comment]
OK, I see -- using a general storage makes sense then.

**Comment by kellertuer** [comment]
At least if you want to aim for the general idea that the Debug/Record/Warnings should be able to reuse the data.
I fear that the approach of storing it in the options in general (you can surely do that for your one solver) would be too much of a rework.

As I wrote, it might be a good idea to introduce `evaluate_` functions for the values we want to cache (cost, gradient,...) and the `get_` functions only evaluate if the value is not yet present. Maybe this requires `CachedOptions` or something, I am not yet sure.
I think this would overall be a good idea, but still needs some thoughts and design things to be solved.

**Comment by kellertuer** [comment]
This is either resolved by #174 or superseded by the #192.
