### ISSUE TITLE
Testing convergence

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#175]
Could we have something similar to `converged` function from Optim.jl? See here: https://github.com/JuliaNLSolvers/Optim.jl/blob/master/src/api.jl#L79 . Optimization.jl would like to have such information.

**Comment by kellertuer** [comment]
Oh, interesting question!

I think Optim.jl has (just a few?) hard coded stopping criteria?

I think this would need two things to be implemented for the quite modular Stopping criteria we have here

* an indicator, whether a stopping criterion is related to convergence – e.g.
  * https://manoptjl.org/stable/plans/stopping_criteria/#Manopt.StopWhenGradientNormLess is a good indicator for convergence, since a small gradient is at least a good indicator
  * https://manoptjl.org/stable/plans/stopping_criteria/#Manopt.StopAfter is not, since it just stops after some time
* We have to adapt that to any/all – the groups of stopping criteria
* Besides stopping criteria one could also write a more general analysis that checks a certain `Option`s (that name will be `SolverState` starting 0.4) which could check additional criteria within some solver state that might indicate convergence.

But maybe for a start implementing this general analysis to only look at the stopping criteria might be a neat first step.

**Comment by mateuszbaran** [comment]
Yes, Optim.jl has much more restrictive stopping criteria than Manopt.jl. It likely wouldn't be particularly difficult to extract such information from `StoppingCriterion` evaluation. I think it would be a nice addition for Manopt 0.4 :slightly_smiling_face: .
