### ISSUE TITLE
Work counters

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#176]
Optim.jl has nice work counters that give number of iterations, calls to objective, gradient, time, etc. It would be nice to be able to obtain such information in Manopt.jl easier than now.

**Comment by kellertuer** [comment]
With the new Objective encapsulation all functions, this will be doable similar to caching for function calls, so that might easily be doable.

For the number of iterations I do not yet have a good idea (it is hidden in some of the stopping criteria, but might be hard to access.

For Time there is https://manoptjl.org/stable/plans/debug/#Manopt.DebugTime (oh with a typo in the docs on the prefix) which we surely can also turn into an action to record said timings accordingly.

For etc. – I do not know what you additionally mean.

**Comment by kellertuer** [comment]
You mean counting their calls?

Sure that would be a `CountingObjective` that encapsulates an `Objective` (the function wrapper in 0.4) and dispatches for `get_cost`.... to count their calls.
If one puts the counter even _inside_ a `CachingObjective` (one of the new features) even less counts are taken, but that can then easily (with dispatch) been done for any part of the objective.

**Comment by mateuszbaran** [comment]
Yes, just counting calls. a `CountingObjective` wrapper sounds like a good idea.

**Comment by kellertuer** [comment]
Even similar to `debug=` one can then in general do a `count=` kwarg for all solvers.

**Comment by kellertuer** [comment]
The number of iterations is already fixed and a first step to solve this, see
https://manoptjl.org/stable/plans/state/#Manopt.get_count
which is also implemented for stopping criteria, which now store the iteration they indicate stop, and since `StopWhenAny` returns its min, `StopWhenAll` returns its max, this is finished.

A next step now is to
* Introduce `CountingObjective` decorator for objectives that counts arbitrary calls of the `get_cost` and `get_gradient` style functions.
* introduce a `CountingState` which is able to do the same for callable things in the state (maybe Linesearch? Subsolvers? ...)

**Comment by mateuszbaran** [comment]
I think that sounds reasonable.
