### ISSUE TITLE
Introduce `default_stepsize(M, O)`

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#180]
The following code demonstrates how conjugate gradient descent fails on Rosenbrock function using default parameters:
```julia
using Manopt
using Manifolds

f_manopt(::Euclidean, x) = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2

function g_manopt!(::Euclidean, storage, x)
    storage[1] = -2.0 * (1.0 - x[1]) - 400.0 * (x[2] - x[1]^2) * x[1]
    storage[2] = 200.0 * (x[2] - x[1]^2)
    return storage
end

M = Euclidean(2)
cg_opts = conjugate_gradient_descent(M, f_manopt, g_manopt!, [0.0, 0.0]; evaluation=MutatingEvaluation(), return_options=true)
```
Could we have default parameters that make it work?

**Comment by kellertuer** [comment]
If you find default parameters that do work – sure; I am not 100% sure where the current default is from, I think those are the ones from Manopt/Matlab.

In general setting good defaults is a really complicated thing to do – and remember that Rosenbrock is a really mean example. But - hehe - this one really explodes fast

```julia
julia> cg_opts = conjugate_gradient_descent(M, f_manopt, g_manopt!, [0.0, 0.0]; evaluation=MutatingEvaluation(), debug=[:Iteration, :Iterate, :Cost, :Stop,"\n"])
Initial F(x): 1.000000
# 1     x: [2.0, 0.0]F(x): 1601.000000
# 2     x: [-3200.0, 800.0]F(x): 10484121674246400.000000
# 3     x: [2.6212863989790594e13, -3.2725775149997744e12]F(x): 47212597681438596372495799766368366330997806787448537088.000000
# 4     x: [-1.4408985664390341e43, 8.994538430325952e41]F(x): 4310559429836373893762014461052062964684649679539072155822222971503375833074684002488557111981322457934557086002722283200061060668117239830893990062402996910678581744400072704.000000
# 5     x: [2.393261832712779e132, -7.46974354390761e130]F(x): Inf
# 6     x: [NaN, NaN]F(x): NaN
```

**Comment by kellertuer** [comment]
Ah, I see that is the same problem as with gradient descent. We have a constant stepsize as default for both

For example with the default. Armijo
```julia
julia> cg_opts = conjugate_gradient_descent(M, f_manopt, g_manopt!, [0.0, 0.0]; evaluation=MutatingEvaluation(), stepsize=ArmijoLinesearch(M),  debug=[:Iteration, :Iterate, :Cost, :Stop,"\n",100])
Initial F(x): 1.000000
# 100   x: [0.3789170183626525, 0.1455948665234621]F(x): 0.386151
# 200   x: [0.4604486280239601, 0.21308291361774606]F(x): 0.291230
# 300   x: [0.5157252480309722, 0.26664128363827033]F(x): 0.234567
# 400   x: [0.5595346370785345, 0.3136420428474512]F(x): 0.194041
# 500   x: [0.5940718838053803, 0.3531472767461153]F(x): 0.164783
The algorithm reached its maximal number of iterations (500).
2-element Vector{Float64}:
 0.5940718838053803
 0.3531472767461153
```

it already looks better. The question here is – whom do we want to annoy with our default?
* people on complicated manifolds, where we have no default retraction
* people on R^n with the constant stepsize

I think we could switch to the first case, since we now have the `default_retraction_method(M)` – the reason to switch to that was, that the old default was `ExponentialRetraction` within Armijo (and that did not have a manifold in its arguments.

**Comment by mateuszbaran** [comment]
I think it's safe to assume that people who would like gradient-based optimization on a manifold do it on a manifold with a reasonable `default_retraction_method(M)`. I wouldn't over-optimize for Rosenbrock but it would be nice to have defaults that make it work sort of OK -- maybe even at the cost of special-casing defaults for R^n. Maybe such defaults would also make sense for other nonpositively-curved manifolds?

**Comment by kellertuer** [comment]
Sure we can switch to Armijo in Manopt 0.4.

The safest way of course could be to have an “empty” default if none is defined (but that is a change to ManifoldsBase) and choose a constant stepsize then. But this means that when defining exp one has to set the default themselves.

**Comment by kellertuer** [comment]
Currently I have no way of checking the curvature before setting the default, so If I would switch for all manifolds to Armijo.

**Comment by mateuszbaran** [comment]
Could we have a `get_default_linesearch(::Manifold, ::Type{<:Options})` function in Manopt 0.4?

**Comment by kellertuer** [comment]
Ah an I would maybe call that `default_stepsize` since there are quite a few rules that do not search at all ;)

**Comment by kellertuer** [comment]
I noticed two problems with this idea.

1) If so we would only defined `default_stepsize(::AbstractManifold, ::MyConcreteSolverState) within Manopt.jl; so later on for specific manifolds one can only overwrite this for a _spefific_ manifold together with a _specific solver_ (or at least a class of manifolds with a specific solver), which I am not sure is that useful.

2) More problematic is how to use this. My idea was to replace the `stepsize=...` now with `stepsize=default_stepsize(M,...)`- but at that point the state does not yet exist it is only generated later in the constructor, so we can not specify the second argument at the point where I wanted to use this.

What should we do about these two points to make is usable and easy to implement?

**Comment by mateuszbaran** [comment]
Hm, I think this shouldn't dispatch on solver state but on solver type. So we may have something like `default_stepsize(::AbstractManifold, ::typeof(quasi_Newton))`. Or we can specify solver type using a new type hierarchy which may be a bit nicer but more complicated to implement. Note that Opimization.jl integration also needs a solver type thing: https://github.com/SciML/Optimization.jl/pull/437/files#diff-91c386d7b5fa9310b5c87114b777bc81e69479305f504a2f361228fd1b6fd8af but it needs to collect more information (e.g. stepsize) so it must be separate.

**Comment by kellertuer** [comment]
Good that I have a hierarchy established for the (former options now) SolverStates, which identify the solver nearly-uniquely. 
With nearly I mean that the solver functions do depend on Problem and State, but in practice State determines the solver. So we could use that also as the type hierarchy for Optimization.jl

I think the type-idea you posted is not 100% correct, since `quasi_Newton` is the high level interface function and I would prefer to use the `AbstractSolverState` type hierarchy at the second argument, but in reality that is also just a minor difference.

**Comment by mateuszbaran** [comment]
So, your idea is to use something like `default_stepsize(::AbstractManifold, ::Type{T}) where T<:AbstractSolverState`? That would also work I think.

**Comment by kellertuer** [comment]
I think that looks also nicer than using the high-level functions like `quasi_Newton` or `DouglasRachford`s types - and we actually can identify the solver based on its State type (as I said that was originally not necessarily intended, since we could have different solvers based on the problem as well). So the I will go with that. Since it is getting late (or dark here at least) I might also just start with that today still (it is a little dull work to introduce that at every solver).

**Comment by mateuszbaran** [comment]
Cool, thanks :slightly_smiling_face: .
