### ISSUE TITLE
cannot use ArmijoLinesearch in complex manifold

### ISSUE THREAD

**Issue by Watayo** [JuliaManifolds/Manopt.jl#197]
We cannot use ArmijoLinesearch for complex Stiefel manifold when executing the gradient_descent solver. (the same phenomena may occur in other complex manifolds)
```
St = Stiefel(2, 2, ℂ)
F(St, x) = real(tr(x' * D))
gradF(St, x) = project(St, x, D)
newW = gradient_descent(St, F, gradF, W; stepsize=ArmijoLinesearch(St))
// newW = gradient_descent(St, F, gradF, W) is same. 
```
where D is partial-derivative of F with respect to W.

Error is here
```
ERROR: LoadError: MethodError: no method matching isless(::Float64, ::ComplexF64)
Closest candidates are:
  isless(::T, ::T) where T<:Union{Float16, Float32, Float64} at float.jl:424
  isless(::AbstractFloat, ::AbstractFloat) at operators.jl:184
  isless(::AbstractFloat, ::Union{StatsBase.PValue, StatsBase.TestStat}) at ~/.julia/packages/StatsBase/XgjIN/src/statmodels.jl:100
  ...
Stacktrace:
  [1] <(x::Float64, y::ComplexF64)
    @ Base ./operators.jl:356
  [2] linesearch_backtrack(M::Manifolds.Stiefel{4, 4, ℂ}, F::Manopt.var"#59#60"{Manopt.DefaultManoptProblem{Manifolds.Stiefel{4, 4, ℂ}, Manopt.ManifoldGradientObjective{Manopt.AllocatingEvaluation, Main.Mera.var"#F#15"{Matrix{ComplexF64}}, Main.Mera.var"#gradF#16"{Matrix{ComplexF64}}}}}, x::Matrix{ComplexF64}, gradFx::Matrix{ComplexF64}, s::Float64, decrease::Float64, contract::Float64, retr::ManifoldsBase.PolarRetraction, η::Matrix{ComplexF64}, f0::Float64; stop_step::Float64)
    @ Manopt ~/.julia/packages/Manopt/a4InU/src/plans/stepsize.jl:272

....
```
Of course, we can use ConstantStepSize in this sample

**Comment by kellertuer** [comment]
Hi,
super cool that you are using Manopt.jl :)
To be fair, I did not test it much with complex manifolds, but I have a good guess what it is.

 I think that might be a problem that stems from `Manifolds.jl` since (thanks for exactly that important precise line) in

https://github.com/JuliaManifolds/Manopt.jl/blob/c42277092aca9427168e7da88b8c42ef3f5b5aae/src/plans/stepsize.jl#L270-L272

You see in l. 272 the `<` that fails and I am very sure that is due to the `inner` in l. 270 returning a complex number, since your cost looks fine.
I can not run your code (I am missing `W`), but you could check whether `inner(M, p, X, Y)` returns a real or a complex number. It should of course return a real number.

and sure your second line yields the same error, since `ArmijoLinesearch` became the default in Manopt 0.4

**Comment by kellertuer** [comment]
...if I am wrong with my assumption and the inner product _can_ be complex, then indeed I have no clue how Armijo should work, because it is checking the linearisation of `F` using the inner product, which then ist just not defined on complex manifolds.

**Comment by Watayo** [comment]
Thank you for quick Reply!
I have done your code in [new issue](https://github.com/JuliaManifolds/Manifolds.jl/issues/566). This returns a complex number. 
Usually, the Euclidean metric of the complex manifold takes the real part of the inner product, so we will expect fixing bugs in manifolds.jl.

**Comment by Watayo** [comment]
In fact, the complex part of Euclidean metric should be very small numerically

**Comment by kellertuer** [comment]
Of course it does, that's what I created ;)

I am also developer over there, so I could easily fix it, I am just not 100% sure (from the theoretical side) whether a metric (or in other words our function `inner` should always be real (or might also be complex). Since the angle

https://github.com/JuliaManifolds/ManifoldsBase.jl/blob/c7e2a17202e3a9db1a483c1c84b41a0ebad8a1ff/src/ManifoldsBase.jl#L132-L140

explicitly includes a real, it might be that we need something like that (but then in a lot of places) here as well. We will have to investigate.

What do you mean by Eucldiean metric? The value from my small example is actually the same as calling `dot(X,Y)` (from `LinearAlgebra`) or `inner(Euclidean(3, 2, ℂ), p, X, Y)` and the result does not have a small complex part (around 0.07 with my randomness that I had).

**Comment by Watayo** [comment]
sorry. I am not an expert on manifolds so I could be wrong.
I want to implement [this](https://arxiv.org/abs/2007.03638) with the manifolds.jl.
I may have mistake taking the definition in this paper as a general definition.

**Comment by Watayo** [comment]
The correct what I say is that I expect at least the matrix manifolds I deal with to satisfy this property.

**Comment by kellertuer** [comment]
Ah, yes, that indicates, that my intuition might be correct that it _is_ real (or maybe at least for Stiefel and Grassmann, but I want to make sure, that _if_ we fix that in Manifolds.jl we fix it for all places where it is wrong.
And if it is correct, I want to make sure, that we provide a function that returns the real part, so that I can fix Armijo :)

So let's wait for the others over on the other issue.

If you are in a hurry I can give you a quick fix, so the linesearch would work.
You could basically redefine inner for yourself (that is only a hack because it is type piracy, but then it would work). If you install Manopt.jl and do 

with
```
using Manifolds, LinearAlgebra # for dot
import Manifodls: inner #we redefine this for the default metric which is Eucliean
inner(M::Stiefel, p, X, Y) = real(dot(X,Y))

M = Stiefel(3, 2, ℂ)
p = rand(M)
X = rand(M; vector_at=p)
Y = rand(M; vector_at=p)
inner(M, p, X, Y) # is: complex – with the redefinition above: real :)
```

**Comment by kellertuer** [comment]
> The correct what I say is that I expect at least the matrix manifolds I deal with to satisfy this property.

I am quite sure it is, but now that I am aware of that, I would like to fix it correctly (and document that) :)

**Comment by Watayo** [comment]
Thank you for all your advice.
I will adopt your suggestion for now. and I look forward to feature development!

**Comment by kellertuer** [comment]
Well, this is an interims fix – you have to start your code with that but then you can continue with your experiment for now :)

I hope we'll figure this one out the next days, should not be too complicated, I already check a few books.

**Comment by kellertuer** [comment]
The trick is the same as described above, we need a `real` around the `inner`. I will provide a fix for that the next days, when I had time to find all occurrences that need to be adapted.

Thanks for reporting this :)
