### ISSUE TITLE
Descent direction reset for CG

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#203]
Some variants of CG have descent direction reset option when it diverges too much from gradient (for example `inner(gradient, descent_direction` is negative). It would be nice to add this option to Manopt.jl.

**Comment by kellertuer** [comment]
Yes that is a typo, the only question then would be – is that a breaking change? I think it is, though it is a bugfix?

**Comment by kellertuer** [comment]
since they are functors, this should be easily doable – add a boolean to the functor struct, indicating that they should reset if...and then test and reset possibly.
Sounds not too hard to do and a nice improvement.

Can you maybe lists which coefficients do that – or at least the ones where you saw that they do that?

**Comment by mateuszbaran** [comment]
Yes, that should be easy. Matlab Manopt does this independently from descent coefficient calculation.

**Comment by kellertuer** [comment]
We could even do a `ResetCoefficient` generic rule that decorates every Coefficients with that basically.

We even have a similar machinery already with the gradient processors that realise Nesterov and these rules.
So maybe a generic CG stepsize (which stores a step size internally) for this would be best then.

**Comment by mateuszbaran** [comment]
Sure, that looks like a good idea.

**Comment by kellertuer** [comment]
I think that should also not be too hard to do, I just have to find time to do it :)
