### ISSUE TITLE
Splitting stochastic gradient descent objective

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#249]
Currently the stochastic gradient descent objective is a single function, in contrast with multi-part gradient. It would be reasonable to also return parts of the objective separately that correspond to specific parts of gradient. That would enable for example using line searches to determine step size.

In your example that would correspond to changing 
```julia
F(M, p) = 1 / (2 * n) * sum(map(q -> distance(M, p, q)^2, data))
```
to
```julia
Fs = [(M, p) -> 1 / 2 * distance(M, p, q)^2 for q in data]
```

**Comment by kellertuer** [comment]
That sounds like a good idea and not that much work, since I think in ALM (or in general the ConstraintObjectives) we have that distinction already, just that Stochastic is far older and I did not yet upgrade it.
On basically just has to distinguish the `Type` of the stochastic_gradient field, whether it is a function or a vector; then we could support both.

Should not be too hard to do, I (or someone) just has to find time. Well-spotted!
