### ISSUE TITLE
possible bug / typo in code

### ISSUE THREAD

**Issue by rs1909** [JuliaManifolds/Manopt.jl#283]
In src/solvers/trust_regions.jl  lines 374 - 379

I believe the terms are meant to be on a single line or at least have parentheses about the whole expression. As it stand the compiler evaluates the first line and then the subsequent lines are calculated and discarded. This is especially true for line 376, which is a complete expression, so the compiler will not continue.

I might be wrong. I've only spotted this because I am frequently having a  
`ERROR: LoadError: ArgumentError: invalid argument #4`  when optimising. This usually indicates that there are NaNs hiding somewhere. Once the solver got through the first 5 or so iterations, it will not occur. It seems that if I put the parentheses, this issue is gone, or I've just been lucky and it would have worked anyway.

**Comment by kellertuer** [comment]
Just to be precise, you are referring to

https://github.com/JuliaManifolds/Manopt.jl/blob/16fd6c0a1295c97e828269a9dc8d3357aa3be094/src/solvers/trust_regions.jl#L372-L380

These lines? Line 376 would just bee `p`?
These lines are fine for me, since every line is one argument to the function. `JuliaFormatter.jl` here splits that into multiple lines, since that would be too long on a single line.

I am not suer about your error, nor why you state the solver would continue with an error? Could you provide a minimal example, where this error occurs, such that I can run the code as well and take a look? I am also not sure where you “put the parenthesis”. Could you provide a bit more detail here?

**Comment by rs1909** [comment]
I am not sure what is with the line numbers, but your reference is very different from what I am looking at. This is the snippet I am looking at, especially the 'modle_value_Cauchy' line

```
        model_value =
            fx + inner(M, trs.p, trs.X, trs.η) + 0.5 * inner(M, trs.p, trs.Hη, trs.η)
        modle_value_Cauchy = fx
        -trs.τ * trs.trust_region_radius * norm_grad
        +0.5 * trs.τ^2 * trs.trust_region_radius^2 / (norm_grad^2) *
        inner(M, trs.p, trs.Hgrad, trs.X)
```

**Comment by rs1909** [comment]
In your link it is line 534...

**Comment by kellertuer** [comment]
Yes, but why are your line numbers then so different ;) ?
Mine are the ones from the current version on the master branch, e.g. I go to https://github.com/JuliaManifolds/Manopt.jl/blob/16fd6c0a1295c97e828269a9dc8d3357aa3be094/src/solvers/trust_regions.jl and select lines on the left (you can also just add `#L123-L456` to get the same)
. But indeed the last 4 lines of 

https://github.com/JuliaManifolds/Manopt.jl/blob/16fd6c0a1295c97e828269a9dc8d3357aa3be094/src/solvers/trust_regions.jl#L532-L537

looks a bit strange (also besides the typo in `modle`. Will try to find time to check that later today – you can also try to fix it yourself of course (remember to run JuliaFormatter) and open a PR of course.

**Comment by kellertuer** [comment]
I think you are correct, that was a typo in the code. If you have time could you check the new PR? The test are still running fine, so they seem not to be affected (much) by this typo;
however, I am also not sure whether this typo is related to the errors you got, since I can not test them myself without an (n)MWE.

**Comment by kellertuer** [comment]
You can now even just update to the new patch version. Let me know whether that also fixes your error message. Feel free to open this again, when there are problems left!

Thanks for reporting this.
