### ISSUE TITLE
Incorrect links in the doc

### ISSUE THREAD

**Issue by fayolle** [JuliaManifolds/Manopt.jl#288]
Some of the links in the [doc](https://manoptjl.org/stable/), in the 'Manifolds' section, seem to be incorrect: 
- 'ManifoldsBase.jl' should point to https://juliamanifolds.github.io/ManifoldsBase.jl/stable/ instead of https://juliamanifolds.github.io/Manifolds.jl/stable/interface.html 
- 'Notation' should point to https://juliamanifolds.github.io/Manifolds.jl/stable/misc/notation.html instead of https://juliamanifolds.github.io/Manifolds.jl/stable/notation.html

**Comment by kellertuer** [comment]
Thanks for pointing those out; indeed we moved those files in the other projects; ManifoldsBase.jl for example was first documented within Manifolds.jl (the old link) before it got its own documentation (the new link)

If you have the time feel free to open a PR; otherwise I will try to find time the next few days.

**Comment by kellertuer** [comment]
Thanks for the remarks, I carefully fixed the two links you mentioned throughout the documentation.
