### ISSUE TITLE
Optimization on a product manifold?

### ISSUE THREAD

**Issue by david-m-rosen** [JuliaManifolds/Manopt.jl#67]
Hi team,

First, let me thank you all for your contributions to both this project and Manifolds.jl -- it's great to have these tools available in Julia!

OK, on to the actual problem :-):  I am trying to solve an optimization problem on the product manifold M = S^2 x Sym(3)  (the product of the 2-dimensional sphere and the set of 3x3 symmetric matrices), and I am having some difficulty determining the right way to specify the problem data so that it plays nicely with Manopt.

My attempted approach corresponds to the following small [minimal_working_example](https://github.com/JuliaManifolds/Manopt.jl/files/6178895/manopt_product_mwe.txt):

Step 1: set up the product manifold and pick an initial point on it:
```
S2 = Sphere(2);
Sym3 = SymmetricMatrices(3);
M = S2 × Sym3;

p0 = ProductRepr(normalize([.25, .25, 0]), Matrix(1.0 * I(3)));
```
Step 2: Set up objective and gradients:
```
g = [1.0; 0.0; 0.0];
I3 = Matrix(1.0 * I(3));

# Set up a simple (linear) objective:  F(x, A) = g⋅x + tr(A)
L(p::ProductRepr) = dot(p.parts[1], g) + tr(p.parts[2]);

# Set up gradient:  gradL = proj_p dL / dp
function gradL(M::ProductManifold, p::ProductRepr)

    return project(M, p, ProductRepr(g, I3));
end
```

Step 3: Set up the plan & options:
```
prob = GradientProblem(M, L, gradL);
opts = GradientDescentOptions(p0);
```
Step 4: Solve!
```
result = solve(prob, opts);
```

However, when I try to run this example, I get the following error message: 

> MethodError: no method matching length(::ProductRepr{Tuple{Array{Float64,1},Array{Float64,2}}})

 which appears to be thrown inside `step_solver!` (`gradient_descent.jl:94`)

That is, Manopt seems not to like my using `ProductRepr` types because these lack a `length` method.

Can you tell me what would be the proper way to do this?

A few other points of note:

* I notice that if I don't include the initial `ProductManifold` argument in my definition of `gradL`, Manopt also complains ... ?
* In the [online documentation](https://juliamanifolds.github.io/Manifolds.jl/stable/features/utilities.html#Manifolds.ProductArray) I see references to various objects like `ShapeSpecification`,  `ProductArray`, `prod_point`, and so on, which seem like they might be viable alternatives here.  But for some reason these do not seem to be present in my current installation of `Manifolds.jl` (although `ProductRepr` is).  For reference, I am using Julia version 1.5.3, and Manifolds version 0.4.17, which I believe is the latest?  (I also tried using the dev version specifically, with the same results).  Do you have any idea what might be going on here?

Any light that you could shed on this would extremely helpful :-)

**Comment by kellertuer** [comment]
Hi David,
well thanks for using Manopt.jl :)

I am surprised, your cost function worked, when I tried, since – to answer your first question – yes, all functions (cost, gradient, probes, hessians) are required to have as first argument the manifold. This is because most inner functions need some information from the manifold anyways and for performance you would then often be required to write a struct and make it a functor.

For `ProductArray` and `ProductRepr`, @mateuszbaran is the expert, I hope we also export ProductArray. But yes 0.4.17 is the latest at the point of your writing, just that 0.4.18 was released this night – not affecting your question. I think `ProductArray` might be complicated since you have to have one type for all your product factors.

To your error, that's an easy fix, that was already available on master (but I just registered 0.3.1, so otherwise just wait a few hours and try that).
Explanation: When I had designed `Manopt.jl` I provided manifolds here directly and all had the possibility to broadcast. So I broadcasted. When we introduced `ManifoldsBase.jl` and I transitioned to use that (maybe last summer) I still had in mind, that all points/tangents are matrices and can be broadcasted, though at that time neither for `ProductRepr` nor for `SVDPoint`/`UMVTVetcor` this holds true. So I just last week changed that but forgot to register this variant.

With 0.3.1 your example runs fine here. Maybe we can also find a way to broadcast on `ProductRepr`, that would be neat, but I currently have no direct idea how to do that.

I hope this helps.

**Comment by mateuszbaran** [comment]
I'll work on broadcasting for `ProductRepr` today, I'll let you know how it turns out.

**Comment by mateuszbaran** [comment]
It seems that I've managed to add custom broadcasting to `ProductRepr` that works here correctly: https://github.com/JuliaManifolds/Manifolds.jl/pull/336/ .

**Comment by david-m-rosen** [comment]
Hi guys,

Thanks very much for your quick reply -- I can confirm that after updating to the latest version of Manopt (and modifying the cost function to accept the manifold as its first argument, as suggested above), the code now runs as intended :-).

However, as no good deed goes unpunished, I have now discovered a new strange behavior XD.  If I run gradient descent on my actual problem with an Armijo line search for a maximum of 50 iterations, I find that the first component of the estimate returned by Manopt does *not* in fact lie on S2:

>  result.options.x
> ProductRepr with 2 submanifold components:
>  Component 1 =
>   3-element Array{Float64,1}:
>    2.174827497484752
>    2.349764420778143
>    0.0
>  Component 2 =
>   3×3 Array{Float64,2}:
>     2.77952  -2.35141  0.0
>    -2.35141   3.85049  0.0
>     0.0       0.0      5.7448

I used a bunch of `RecordActions` to instrument Manopt as it was running, and as far as I can tell, it looks like this behavior is due to a gradual loss of normalization in the sphere component of the iterates as the algorithm runs.  This effect starts to become  pronounced around iteration 36:

![sphere component norms](https://user-images.githubusercontent.com/20913542/112047330-88ca2f00-8b23-11eb-8c40-f61e64832552.png)

**Update**: After digging around a bit, it looks like the implementation of the exponential map for Spheres in Manifold.jl does *not* enforce the normalization of the returned point -- check out lines 181-187 of Spheres.jl.  I think this is probably the culprit XD.

I'd be happy to take a crack at putting together a small patch/pull request to update this function accordingly (using the `project` function), if that sounds good to you guys :-)?

**Comment by kellertuer** [comment]
Great that the first fix worked.

For the sphere – yes I know, we do not check, whether the input point `p` for `exp!` is a unit vector and yes that breaks if it is not. Until now I assumed usually, that the user takes care of that, since if you enter with `p` being on S2, the result ing `q` is, too; we even have extensive tests for that.  

So then the question is, why is your `p` “degrading” in the first place? I think that might maybe happen somewhere else? But sure, I'd be happy if you would investigate, but to keep the number of allocations and FLOPS down, I would prefer if we find a way to not put a `project!` into `exp!` if possible.

**Comment by NicolasBoumal** [comment]
Hey guys!

This got me worried that maybe exp for the sphere in the Matlab version of Manopt would have a drift (because we do not "reproject" there either), but apparently it's fine:

```
>> M = spherefactory(20);
>> x = M.rand();
>> for k = 1 : 10000,
       x = M.exp(x, M.randvec(x));
end
>> norm(x)

ans =

     1
```

I'll admit, the above is in part a thinly veiled excuse to ask: Dave, can you tell us a bit about your application? (If this is an unacceptable hijack of the issues board, we can take it offline; well, on another line.)

Cheers,
Nicolas


```
% Exponential on the sphere
function y = exponential(x, d, t)

    if nargin == 2
        % t = 1
        td = d;
    else
        td = t*d;
    end
    
    nrm_td = norm(td, 'fro');
    
    % Former versions of Manopt avoided the computation of sin(a)/a for
    % small a, but further investigations suggest this computation is
    % well-behaved numerically.
    if nrm_td > 0
        y = x*cos(nrm_td) + td*(sin(nrm_td)/nrm_td);
    else
        y = x;
    end

end
```

**Comment by kellertuer** [comment]
Thanks for checking @NicolasBoumal , maybe ours is currently faster in number for operations but might have an instability drift (since a while back we switched from x cos + t sin(...) for exactly that reason) to something more sophisticated. Let's take a look the next few days.

**Comment by kellertuer** [comment]
Here's my approach to a drift-test

````
using Manopt, Manifolds, Random
Random.seed!(42)

M = Sphere(20)
x = random_point(M)
n = norm(x)
for _ ∈ 1:1000
    exp!(M, x, x, random_tangent(M,x))
end
println("before: $n, and after: $(norm(x))")
````

which
* for `1000` yields `before: 1.0, and after: 1.0`
* for `1e4` yields `before: 1.0, and after: 0.9999999999999999`
* for  `1e5` (as well as `1e6` yields) `before: 1.0, and after: 0.9999999999999998`

so - ahem - we might have a drift, yes.

**Comment by david-m-rosen** [comment]
Alright, well this is starting to look like a problem on my end then XD.  

@NicolasBoumal  [Hey :-)! ]  I'm using analytic derivatives that I've checked with auto-differentiation, but I implemented these as standalone functions (i.e., without reference to Manifolds or Manopt), using a somewhat naive method for the orthogonal projection step [ (I - xx') * g ].  Perhaps this introduces enough "slop" into the computations that it causes a noticeable lack of orthogonality ... 

Let me double-check this and I'll update the thread XD

**Comment by david-m-rosen** [comment]
OK, after using a more careful orthogonal projection I can confirm that this now works as expected.  Sorry for the false alarm guys XD.

**Comment by kellertuer** [comment]
Nice! Well, At least I know that we drift just slightly, though not much. Better check once too much than having wrong code :)
